

****SetupDates******;

%LET UID=;
%LET TDP1PWD=;
%LET TDP3PWD=;

/* Define Options and global macro variables */
OPTIONS MPRINT MLOGIC NOSYMBOLGEN COMPRESS=NO MINOPERATOR ;
%GLOBAL MONTH CURMTH LASTMTH MTHDT MTHDTS MONTHKEYZ MONTHKEY MONTHKEYL 
        MTHYR MTHDT2 MTHDT3 EOM EOMLAST MONTHKEYQ TMTHDT TMAXMTH   WFDR PRPDR  RFDR     ;

/* To run last month's data month=-1 */
%LET MONTH=-1;

/* Setup up monthly macro variables */
%MACRO SETUP(MY) ; %MACRO __() ; %MEND __ ;
	
	%LET CURMTH=%SYSFUNC(INTNX(MONTH,"&SYSDATE"D,&MY.,END)); 
	%LET LASTMTH=%SYSFUNC(INTNX(MONTH,"&SYSDATE"D, ( (  &MY. )-1)       ,B)); 
	%LET MTHDT=%SYSFUNC(PUTN(&CURMTH,YYMMDD10.));  
	%LET MONTHKEYZ=%SYSFUNC(PUTN(&CURMTH,YYMMDDN8.)); 
	%LET MTHDTS=%SYSFUNC (PUTN(&CURMTH,MONYY5.));  
	%LET MTHYR=%SYSFUNC(PUTN(&CURMTH,MONYY7.));  
	%LET MONTHKEY=%SYSFUNC(PUTN(&CURMTH,YYMMN6.));  
	%LET MONTHKEYL=%SYSFUNC(PUTN(&LASTMTH,YYMMN6.));  
	%LET MTHDT2=%SYSFUNC(PUTN(&CURMTH,DATE9.));
	%LET MTHDT3=%SYSFUNC(PUTN(&LASTMTH,DATE9.));
	%LET TMTHDT=DATE %UNQUOTE(%BQUOTE(')&MTHDT.%BQUOTE('));	
	%LET EOM=%UNQUOTE(%BQUOTE(')&MTHDT2.%BQUOTE('))D;	
	%LET EOMLAST=%UNQUOTE(%BQUOTE(')&MTHDT3.%BQUOTE('))D;	
	%LET MONTHKEYQ=%UNQUOTE(%BQUOTE(')&MONTHKEY.%BQUOTE('));	
	%LET TMAXMTH =DATE '2999-12-31';

%MEND SETUP ;

%SETUP(&MONTH.);

%put &MONTHKEY.;
%put &MONTHKEYL.;
*added Git test change here *;
*added another change *;


